# Generated by Django 4.2.5 on 2023-09-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=24, unique=True)),
                ('email', models.TextField(unique=True)),
                ('password', models.CharField(max_length=24)),
                ('role', models.CharField(max_length=40)),
            ],
        ),
    ]
