# Generated by Django 4.2.5 on 2023-10-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saedah', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
