# Generated by Django 4.2.5 on 2023-10-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saedah', '0002_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='voucher',
        ),
    ]
