# Generated by Django 4.2.5 on 2023-10-15 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saedah', '0003_user_avatar_dealphotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='deal',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvoted_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_deals', to=settings.AUTH_USER_MODEL),
        ),
    ]
