# Generated by Django 4.2.5 on 2023-10-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saedah', '0003_remove_deal_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='tags',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
