# Generated by Django 4.2.5 on 2023-10-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saedah', '0005_deal_link_alter_deal_latitude_alter_deal_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='link',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
