# Generated by Django 4.2.5 on 2023-10-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saedah', '0006_deal_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='isLiked',
            field=models.BooleanField(default=False),
        ),
    ]
