# Generated by Django 4.2.5 on 2023-10-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saedah', '0006_alter_deal_latitude_alter_deal_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
